# Site settings
title: Reinier Hartog
email: rmhartog@rmhartog.me
url: https://www.rmhartog.me
description: "Reinier Hartog's personal landing page"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Reinier M. Hartog

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/rm_hartog
  - title: github
    url: https://github.com/rmhartog

# Build settings
markdown: kramdown
permalink: pretty
